export default function modalSearch({ search, onSearch }) {
  var listSearch = [
    "Toyota iQ",
    "Mitsubishi Lancer",
    "Vauxhall Agila",
    "Hyundai Getz",
    "Honda Jazz",
    "Hyundai i10",
    "Nissan Almera Tino",
    "Hyundai i20",
    "Citroen C1",
    "Suzuki Alto",
    "Honda Insight",
    "Ford Ka",
    "Kia Picanto",
    "Ford Focus",
    "Mazda MX-5",
    "CHEVROLET KALOS",
    "Peugeot 107",
    "Mazda 2",
    "Toyota Yaris",
    "Volkswagen Polo",
    "Mercedes-Benz CLC",
    "Seat Ibiza",
    "Ford Fusion",
    "Honda Civic",
    "Toyota Prius",
    "Honda Accord",
    "Nissan Almera",
    "Toyota Aygo",
    "Ford Fiesta",
    "Hyundai i30",
    "Peugeot Partner Tepee",
    "Suzuki Jimny",
    "Vauxhall Tigra",
    "Kia Ceed",
    "Vauxhall Zafira",
    "Nissan Note",
    "Kia Rio",
    "Mitsubishi Colt",
    "Toyota Corolla",
    "Nissan Qashqai+2",
    "Citroen C3 Picasso",
    "Citroen Berlingo First",
    "Renault Twingo",
    "Nissan Micra",
    "Renault Scenic",
    "Toyota Auris",
    "Audi TT",
    "Mazda 3",
    "Skoda Fabia",
    "Citroen Xsara Picasso",
    "Renault Kangoo",
    "Citroen Berlingo Multispace",
    "Volkswagen Fox",
    "Suzuki Splash",
    "Suzuki SX4",
    "Smart Fortwo",
    "Ford C-Max",
    "Rover 25",
    "Mercedes-Benz E-Class",
    "FORD MONDEO",
    "Lexus GS",
    "Renault Grand Modus",
    "Honda CR-V",
    "Suzuki Grand Vitara",
    "CHEVROLET TACUMA",
    "Volkswagen Beetle",
    "Toyota Avensis",
    "Fiat Punto",
    "Renault Clio",
    "Citroen C3",
    "Mazda 6",
    "Chevrolet Matiz",
    "Volvo C30",
    "Renault Clio Campus",
    "Renault Megane",
    "Vauxhall Meriva",
    "Fiat Panda",
    "Chevrolet Aveo",
    "Volkswagen Golf",
    "Lexus RX",
    "Audi A4 Allroad",
    "Suzuki Swift",
    "Skoda Roomster",
    "Nissan Qashqai",
    "Citroen C2",
    "Mercedes-Benz C-Class",
    "Volvo S80",
    "CHRYSLER PT CRUISER",
    "Peugeot 206 CC",
    "Chevrolet Cruze",
    "Renault Laguna",
    "Hyundai Tucson",
    "Renault Koleos",
    "Fiat 500",
    "Lexus IS",
    "Alfa Romeo GIULIETTA",
    "Volvo V70",
    "Lexus LS",
    "Vauxhall Astra",
    "Citroen C-Crosser",
  ];
  return (
    <div
      style={{
        backgroundColor: "rgb(255 255 255)",
        width: "100%",
        height: "82vh",
        position: "fixed",
        zIndex: "10",
        top: "90px",
        padding: "20px",
        display: onSearch ? onSearch : "none",
      }}
    >
      {listSearch
        .filter((name) => name.includes(search))
        .map((filteredName, index) => {
          return index < 10 ? <p>{filteredName}</p> : "";
        })}
    </div>
  );
}
